name: Test Cpp Action

on: [push, pull_request]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: cpp-action1
        uses: ./.github/actions/cpp-action1
